# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_contracts.analyse_resume_pb2 as analyse__resume__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analyse_resume_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyseResumeStub(object):
    """The service definition - what functions are available
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeResume = channel.unary_unary(
                '/analyse_resume.AnalyseResume/AnalyzeResume',
                request_serializer=analyse__resume__pb2.AnalyseResumeRequest.SerializeToString,
                response_deserializer=analyse__resume__pb2.AnalyseResumeResponse.FromString,
                _registered_method=True)


class AnalyseResumeServicer(object):
    """The service definition - what functions are available
    """

    def AnalyzeResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyseResumeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeResume': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeResume,
                    request_deserializer=analyse__resume__pb2.AnalyseResumeRequest.FromString,
                    response_serializer=analyse__resume__pb2.AnalyseResumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyse_resume.AnalyseResume', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analyse_resume.AnalyseResume', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyseResume(object):
    """The service definition - what functions are available
    """

    @staticmethod
    def AnalyzeResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analyse_resume.AnalyseResume/AnalyzeResume',
            analyse__resume__pb2.AnalyseResumeRequest.SerializeToString,
            analyse__resume__pb2.AnalyseResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
