# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyse_resume.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analyse_resume.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61nalyse_resume.proto\x12\x0e\x61nalyse_resume\"P\n\x14\x41nalyseResumeRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x17\n\x0fjob_description\x18\x03 \x01(\t\"\xf3\x01\n\x15\x41nalyseResumeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bmatch_score\x18\x02 \x01(\x01\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x03 \x01(\t\x12\x18\n\x10missing_keywords\x18\x04 \x03(\t\x12R\n\x0fskills_analysis\x18\x05 \x03(\x0b\x32\x39.analyse_resume.AnalyseResumeResponse.SkillsAnalysisEntry\x1a\x35\n\x13SkillsAnalysisEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32m\n\rAnalyseResume\x12\\\n\rAnalyzeResume\x12$.analyse_resume.AnalyseResumeRequest\x1a%.analyse_resume.AnalyseResumeResponseB\x1e\xaa\x02\x1b\x41tsScorer.Api.GrpcContractsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyse_resume_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\033AtsScorer.Api.GrpcContracts'
  _globals['_ANALYSERESUMERESPONSE_SKILLSANALYSISENTRY']._loaded_options = None
  _globals['_ANALYSERESUMERESPONSE_SKILLSANALYSISENTRY']._serialized_options = b'8\001'
  _globals['_ANALYSERESUMEREQUEST']._serialized_start=40
  _globals['_ANALYSERESUMEREQUEST']._serialized_end=120
  _globals['_ANALYSERESUMERESPONSE']._serialized_start=123
  _globals['_ANALYSERESUMERESPONSE']._serialized_end=366
  _globals['_ANALYSERESUMERESPONSE_SKILLSANALYSISENTRY']._serialized_start=313
  _globals['_ANALYSERESUMERESPONSE_SKILLSANALYSISENTRY']._serialized_end=366
  _globals['_ANALYSERESUME']._serialized_start=368
  _globals['_ANALYSERESUME']._serialized_end=477
# @@protoc_insertion_point(module_scope)
